# Generated by Django 2.2.6 on 2019-10-24 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Festa', '0002_auto_20191023_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Aluguel',
            new_name='Aluguel_cliente',
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Festa.Tema'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.DateField(verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.TimeField(verbose_name='Telefone'),
        ),
    ]
