# Generated by Django 2.2.6 on 2019-10-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Festa', '0003_auto_20191024_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='uf',
            field=models.CharField(choices=[('PI', 'Piaui'), ('SP', 'São Paulo'), ('CE', 'Ceará'), ('MA', 'Maranhão'), ('PE', 'Pernambuco')], default='PI', max_length=10, verbose_name='UF'),
        ),
    ]
